# Generated by Django 5.0.3 on 2025-11-03 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the report')),
                ('total_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('avg_session_duration', models.FloatField(default=0.0, help_text='Average session duration in seconds')),
                ('top_referrers', models.JSONField(default=list, help_text='Top referrers with counts')),
                ('top_pages', models.JSONField(default=list, help_text='Top pages/sections viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('portfolio', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(help_text='ID of clicked element', max_length=100)),
                ('element_type', models.CharField(blank=True, help_text='Type of element (button, link, project, etc.)', max_length=50)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['portfolio', '-clicked_at'], name='analytics_c_portfol_f46da9_idx'), models.Index(fields=['element_type', '-clicked_at'], name='analytics_c_element_069d11_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(default=0, help_text='View duration in seconds')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['portfolio', '-viewed_at'], name='analytics_p_portfol_c3467b_idx'), models.Index(fields=['viewed_at'], name='analytics_p_viewed__606bdf_idx')],
            },
        ),
    ]
