# Generated by Django 5.0.3 on 2025-11-03 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(help_text='Raw extracted text from resume')),
                ('structured_data', models.JSONField(default=dict, help_text='Structured resume data (name, email, phone, experience, education, etc.)')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='resumes.resumeupload')),
            ],
            options={
                'verbose_name': 'Resume Data',
                'verbose_name_plural': 'Resume Data',
            },
        ),
        migrations.CreateModel(
            name='ParsedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skills'), ('language', 'Languages'), ('framework', 'Frameworks'), ('tool', 'Tools'), ('other', 'Other')], default='technical', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence score (0.0 to 1.0)')),
                ('resume_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resumes.resumedata')),
            ],
            options={
                'ordering': ['-confidence_score', 'name'],
                'unique_together': {('resume_data', 'name')},
            },
        ),
    ]
