# Generated by Django 5.0.3 on 2025-11-03 15:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimalist', 'Minimalist'), ('developer', 'Developer'), ('designer', 'Designer')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='templates/previews/')),
                ('config', models.JSONField(default=dict, help_text='Template configuration (colors, fonts, layouts, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('template_type', models.CharField(default='modern', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('custom_settings', models.JSONField(default=dict, help_text='Custom portfolio settings (colors, fonts, etc.)')),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolios.template')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('secondary_color', models.CharField(default='#ffffff', max_length=7)),
                ('accent_color', models.CharField(default='#007bff', max_length=7)),
                ('font_family', models.CharField(default='Inter', max_length=100)),
                ('font_size', models.CharField(default='16px', max_length=20)),
                ('custom_logo', models.ImageField(blank=True, null=True, upload_to='portfolios/logos/')),
                ('custom_background', models.ImageField(blank=True, null=True, upload_to='portfolios/backgrounds/')),
                ('custom_css', models.TextField(blank=True, help_text='Global custom CSS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('header', 'Header'), ('about', 'About'), ('skills', 'Skills'), ('projects', 'Projects'), ('blog', 'Blog'), ('contact', 'Contact'), ('custom', 'Custom')], max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order in portfolio', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_visible', models.BooleanField(default=True)),
                ('content', models.JSONField(default=dict, help_text='Component content data')),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS for this component')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('portfolio', 'component_type', 'order')},
            },
        ),
    ]
