# Generated by Django 5.0.3 on 2025-11-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='interactive_elements',
            field=models.JSONField(default=dict, help_text='Interactive features configuration (animations, effects, etc.)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO meta keywords', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='navigation_enabled',
            field=models.BooleanField(default=True, help_text='Enable navigation between pages/sections'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pages',
            field=models.JSONField(default=list, help_text='Multi-page structure configuration'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='portfolios/profiles/'),
        ),
    ]
