# Generated by Django 5.0.3 on 2025-11-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_portfolio_interactive_elements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocomponent',
            name='component_type',
            field=models.CharField(
                choices=[
                    ('header', 'Header'),
                    ('about', 'About'),
                    ('skills', 'Skills'),
                    ('projects', 'Projects'),
                    ('blog', 'Blog'),
                    ('contact', 'Contact'),
                    ('custom', 'Custom'),
                    ('hero_banner', 'Hero Banner'),
                    ('about_me_card', 'About Me Card'),
                    ('skills_cloud', 'Skills Cloud'),
                    ('experience_timeline', 'Experience Timeline'),
                    ('project_grid', 'Project Grid'),
                    ('services_section', 'Services Section'),
                    ('achievements_counters', 'Achievements Counters'),
                    ('testimonials_carousel', 'Testimonials Carousel'),
                    ('blog_preview_grid', 'Blog Preview Grid'),
                    ('contact_form', 'Contact Form'),
                    ('footer', 'Footer'),
                ],
                max_length=25
            ),
        ),
    ]

